# Generated by Django 2.0 on 2018-09-05 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='read_name',
            field=models.IntegerField(default=0, verbose_name='阅读数'),
        ),
    ]
