# Generated by Django 2.0 on 2018-09-01 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180902_0136'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='content',
            field=models.TextField(default=None, verbose_name='内容'),
        ),
    ]
