# Generated by Django 2.0 on 2018-09-05 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blog_read_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='read_name',
            new_name='read_num',
        ),
    ]
